import createConspiracyEngine from './engine.js?v=clue-grid-2';
const $=s=>document.querySelector(s), board=$('#board'),cardsLayer=$('#cards'),threadGroup=$('#threads g');
const workspace=$('.workspace'),analysis=$('#analysis'),findingsToggle=$('#findingsToggle');
let engine,boardData={nodes:[],edges:[]},connecting=false,firstNode=null,drag=null;
const rotations=[-4.8,3.2,-2.6,4.1,-3.4,2.7,-1.8];
const toast=text=>{const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
const parse=method=>JSON.parse(engine[method]());
function sync(){boardData=parse('boardJSON');render()}
function render(){cardsLayer.innerHTML='';boardData.nodes.forEach((node,i)=>{const card=document.createElement('article');card.className='card';card.dataset.id=node.id;card.dataset.type=node.type;card.style.left=`${node.x}%`;card.style.top=`${node.y}%`;card.style.setProperty('--rot',`${rotations[i%rotations.length]}deg`);card.innerHTML=`<small><span>${node.type.toUpperCase()}</span><span>#${String(node.id).padStart(3,'0')}</span></small><h3>${escapeHTML(node.title)}</h3><p>${escapeHTML(node.detail)}</p><div class="confidence"><i style="width:${node.confidence*100}%"></i></div>`;card.addEventListener('pointerdown',startDrag);card.addEventListener('click',chooseConnection);cardsLayer.append(card)});requestAnimationFrame(drawThreads)}
function drawThreads(){threadGroup.innerHTML='';const rect=board.getBoundingClientRect();boardData.edges.forEach(edge=>{const a=cardsLayer.querySelector(`[data-id="${edge.source}"]`),b=cardsLayer.querySelector(`[data-id="${edge.target}"]`);if(!a||!b)return;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.left-rect.left+ar.width/2,y1=ar.top-rect.top+8,x2=br.left-rect.left+br.width/2,y2=br.top-rect.top+8;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('class',`thread ${edge.verified?'verified':''}`);threadGroup.append(line);const label=document.createElementNS('http://www.w3.org/2000/svg','text');const dx=x2-x1,dy=y2-y1,length=Math.hypot(dx,dy)||1,offset=12;label.setAttribute('x',(x1+x2)/2+(-dy/length)*offset);label.setAttribute('y',(y1+y2)/2+(dx/length)*offset);label.setAttribute('text-anchor','middle');label.setAttribute('class','threadLabel');label.textContent=edge.label;threadGroup.append(label)})}
function startDrag(event){if(connecting)return;event.currentTarget.setPointerCapture(event.pointerId);const rect=board.getBoundingClientRect(),card=event.currentTarget;drag={card,id:+card.dataset.id,ox:event.clientX-card.getBoundingClientRect().left,oy:event.clientY-card.getBoundingClientRect().top,rect};card.addEventListener('pointermove',moveDrag);card.addEventListener('pointerup',endDrag,{once:true})}
function moveDrag(event){if(!drag)return;const x=Math.max(0,Math.min(drag.rect.width-drag.card.offsetWidth,event.clientX-drag.rect.left-drag.ox)),y=Math.max(30,Math.min(drag.rect.height-drag.card.offsetHeight,event.clientY-drag.rect.top-drag.oy));drag.card.style.left=`${x}px`;drag.card.style.top=`${y}px`;drawThreads()}
function endDrag(event){if(!drag)return;drag.card.removeEventListener('pointermove',moveDrag);const x=parseFloat(drag.card.style.left)/drag.rect.width*100,y=parseFloat(drag.card.style.top)/drag.rect.height*100;engine.updatePosition(drag.id,x,y);drag=null;sync()}
function chooseConnection(event){if(!connecting)return;event.stopPropagation();const id=+event.currentTarget.dataset.id;if(firstNode===null){firstNode=id;event.currentTarget.classList.add('selected');$('#connectHint').textContent='NOW SELECT THE SECOND CLUE'}else if(id!==firstNode){engine.addEdge(firstNode,id,'new red thread',.7,false);connecting=false;firstNode=null;board.classList.remove('connecting');$('#connectBtn').classList.remove('active');toast('CONNECTION ADDED');sync()}}
function toggleConnect(){connecting=!connecting;firstNode=null;board.classList.toggle('connecting',connecting);$('#connectBtn').classList.toggle('active',connecting);document.querySelectorAll('.card').forEach(x=>x.classList.remove('selected'));$('#connectHint').textContent='SELECT THE FIRST CLUE'}
function arrangeCards(open){if(!engine||!boardData.nodes.length)return;const slots=open?[[4,5],[54,8],[8,29],[57,33],[3,54],[52,58],[28,77]]:[[6,10],[39,6],[70,15],[28,39],[5,65],[63,47],[42,73]];boardData.nodes.forEach((node,index)=>{const slot=slots[index%slots.length];engine.updatePosition(node.id,slot[0],slot[1])});sync()}
function setFindings(open){analysis.classList.toggle('open',open);workspace.classList.toggle('findings-open',open);findingsToggle.setAttribute('aria-expanded',String(open));findingsToggle.textContent=open?'CLOSE':'FINDINGS';arrangeCards(open)}
function analyze(){const result=parse('analyzeJSON'),center=boardData.nodes.find(n=>n.id===result.centralNode);$('#score').textContent=String(Math.round(result.suspicionScore)).padStart(2,'0');$('#nodeMetric').textContent=result.nodeCount;$('#edgeMetric').textContent=result.edgeCount;$('#clusterMetric').textContent=result.componentCount;$('#narrative').textContent=result.narrative;$('#centralName').textContent=center?.title||'No clear center';$('#finding').textContent=result.suspicionScore>68?'This is becoming difficult to dismiss.':result.suspicionScore>45?'There is definitely a shape here.':'Mostly coincidence. For now.';setFindings(true)}
function addClue(form){const data=new FormData(form),rect=board.getBoundingClientRect(),id=engine.addNode(data.get('title'),data.get('detail')||'No explanation was attached.',data.get('type'),32+Math.random()*35,28+Math.random()*35,+data.get('confidence')/100);engine.addTag(id,'user-added');form.reset();sync();toast('EVIDENCE PINNED')}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function boot(){try{const Module=await createConspiracyEngine({locateFile:path=>path});engine=new Module.GraphEngine();engine.loadDemoCase();sync();arrangeCards(false)}catch(error){console.error('Graph engine failed to initialize',error);toast('CASE ENGINE COULD NOT START')}}
$('#addBtn').onclick=()=>$('#clueDialog').showModal();$('#analyzePanelBtn').addEventListener('click',event=>{event.preventDefault();analyze()});$('#connectBtn').onclick=toggleConnect;$('#analyzeBtn').onclick=analyze;$('#closeAnalysis').onclick=()=>setFindings(false);findingsToggle.onclick=()=>setFindings(!analysis.classList.contains('open'));$('#resetBtn').onclick=()=>{engine.loadDemoCase();connecting=false;board.classList.remove('connecting');sync();arrangeCards(analysis.classList.contains('open'));toast('FRESH CASE LOADED')};$('#clueForm').addEventListener('submit',event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();addClue(event.currentTarget);$('#clueDialog').close()});window.addEventListener('resize',drawThreads);boot();
